### ISSUE TITLE
Some Recommendations and Suggestions for Bot #2

### ISSUE THREAD

**Issue by Dark25** [gosimulate/gosimulator#132]
Add candy to see pokemones trapped next to the IV to know how many sweets have in each pokemon , so developments would be configured more easily.

and with that the bot would be almost perfect .

**Comment by PeggerWed** [comment]
An option to let the user choose if it wants pokemon transffers!

Transffer pokemon on/off
or
Transffer pokemon if more then 15 (or 20) in bag

I like to evolve manually with my lucky egg and since you can evolve 2 pokemon in a minute, i always stack up till i know for sure i can evolve 120 pokemon ((it's less if the evolved pokemon isn't in your pokedex yet)
