### ISSUE TITLE
Medals and hatched eggs cause error

### ISSUE THREAD

**Issue by neospeed83** [gosimulate/gosimulator#343]
My bot was working fine but suddenly saw something went wrong again. Went into the game from official app and found that I've gotten few medals and 2 eggs hatched. (P.s Hatch eggs was on) this made bot to show error plz fix this :)

**Comment by manor7777** [comment]
Can you provide screenshots or more details of the error please @neospeed83

**Comment by narutouchi55** [comment]
Maybe you are out of pokeballs or out of Rasperries

**Comment by neospeed83** [comment]
@manor7777 i will try to add screenshots the next time it happens. 
and  I'm not out of pokeballs or raspberries. @narutouchi55

**Comment by neospeed83** [comment]
According to me the hatched eggs dont get collected properly bcuz you have to touch them to hatch.. there were 3 medals to be exact and after i closed the official app(after collecting medals and eggs) the bot then started to work fine again.

**Comment by manor7777** [comment]
@neospeed83 i know you have to click on the eggs to hatch them, but i think that is intentional on niantic as your supposed to be in the game to hatch them.  I found that it works better if i turn off location services, turn off hatching eggs in the bot, and put them in incubators manually, they will hatch and the bot shouldn't give you an error, but you still need to click on them to fully hatch them when you open the app, but it will still count your distance walking even with hatching eggs off in the bot.
